// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string zip = 3;</code>
   * @return The zip.
   */
  java.lang.String getZip();
  /**
   * <code>string zip = 3;</code>
   * @return The bytes for zip.
   */
  com.google.protobuf.ByteString
      getZipBytes();

  /**
   * <code>string street = 4;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 4;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();
}
