// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

/**
 * Protobuf type {@code CartItems}
 */
public final class CartItems extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CartItems)
    CartItemsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CartItems.newBuilder() to construct.
  private CartItems(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CartItems() {
    cartProducts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CartItems();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CartItems(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              cartProducts_ = new java.util.ArrayList<org.dataaccess.protobuf.Cart>();
              mutable_bitField0_ |= 0x00000001;
            }
            cartProducts_.add(
                input.readMessage(org.dataaccess.protobuf.Cart.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        cartProducts_ = java.util.Collections.unmodifiableList(cartProducts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.dataaccess.protobuf.Protobuf.internal_static_CartItems_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.dataaccess.protobuf.Protobuf.internal_static_CartItems_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.dataaccess.protobuf.CartItems.class, org.dataaccess.protobuf.CartItems.Builder.class);
  }

  public static final int CARTPRODUCTS_FIELD_NUMBER = 1;
  private java.util.List<org.dataaccess.protobuf.Cart> cartProducts_;
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.dataaccess.protobuf.Cart> getCartProductsList() {
    return cartProducts_;
  }
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.dataaccess.protobuf.CartOrBuilder> 
      getCartProductsOrBuilderList() {
    return cartProducts_;
  }
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  @java.lang.Override
  public int getCartProductsCount() {
    return cartProducts_.size();
  }
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  @java.lang.Override
  public org.dataaccess.protobuf.Cart getCartProducts(int index) {
    return cartProducts_.get(index);
  }
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  @java.lang.Override
  public org.dataaccess.protobuf.CartOrBuilder getCartProductsOrBuilder(
      int index) {
    return cartProducts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cartProducts_.size(); i++) {
      output.writeMessage(1, cartProducts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cartProducts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cartProducts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.dataaccess.protobuf.CartItems)) {
      return super.equals(obj);
    }
    org.dataaccess.protobuf.CartItems other = (org.dataaccess.protobuf.CartItems) obj;

    if (!getCartProductsList()
        .equals(other.getCartProductsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCartProductsCount() > 0) {
      hash = (37 * hash) + CARTPRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getCartProductsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.dataaccess.protobuf.CartItems parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dataaccess.protobuf.CartItems parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.dataaccess.protobuf.CartItems parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dataaccess.protobuf.CartItems parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.dataaccess.protobuf.CartItems prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CartItems}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CartItems)
      org.dataaccess.protobuf.CartItemsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dataaccess.protobuf.Protobuf.internal_static_CartItems_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dataaccess.protobuf.Protobuf.internal_static_CartItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dataaccess.protobuf.CartItems.class, org.dataaccess.protobuf.CartItems.Builder.class);
    }

    // Construct using org.dataaccess.protobuf.CartItems.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCartProductsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cartProductsBuilder_ == null) {
        cartProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cartProductsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.dataaccess.protobuf.Protobuf.internal_static_CartItems_descriptor;
    }

    @java.lang.Override
    public org.dataaccess.protobuf.CartItems getDefaultInstanceForType() {
      return org.dataaccess.protobuf.CartItems.getDefaultInstance();
    }

    @java.lang.Override
    public org.dataaccess.protobuf.CartItems build() {
      org.dataaccess.protobuf.CartItems result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.dataaccess.protobuf.CartItems buildPartial() {
      org.dataaccess.protobuf.CartItems result = new org.dataaccess.protobuf.CartItems(this);
      int from_bitField0_ = bitField0_;
      if (cartProductsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cartProducts_ = java.util.Collections.unmodifiableList(cartProducts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cartProducts_ = cartProducts_;
      } else {
        result.cartProducts_ = cartProductsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.dataaccess.protobuf.CartItems) {
        return mergeFrom((org.dataaccess.protobuf.CartItems)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.dataaccess.protobuf.CartItems other) {
      if (other == org.dataaccess.protobuf.CartItems.getDefaultInstance()) return this;
      if (cartProductsBuilder_ == null) {
        if (!other.cartProducts_.isEmpty()) {
          if (cartProducts_.isEmpty()) {
            cartProducts_ = other.cartProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCartProductsIsMutable();
            cartProducts_.addAll(other.cartProducts_);
          }
          onChanged();
        }
      } else {
        if (!other.cartProducts_.isEmpty()) {
          if (cartProductsBuilder_.isEmpty()) {
            cartProductsBuilder_.dispose();
            cartProductsBuilder_ = null;
            cartProducts_ = other.cartProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cartProductsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCartProductsFieldBuilder() : null;
          } else {
            cartProductsBuilder_.addAllMessages(other.cartProducts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.dataaccess.protobuf.CartItems parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.dataaccess.protobuf.CartItems) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.dataaccess.protobuf.Cart> cartProducts_ =
      java.util.Collections.emptyList();
    private void ensureCartProductsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cartProducts_ = new java.util.ArrayList<org.dataaccess.protobuf.Cart>(cartProducts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.dataaccess.protobuf.Cart, org.dataaccess.protobuf.Cart.Builder, org.dataaccess.protobuf.CartOrBuilder> cartProductsBuilder_;

    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public java.util.List<org.dataaccess.protobuf.Cart> getCartProductsList() {
      if (cartProductsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cartProducts_);
      } else {
        return cartProductsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public int getCartProductsCount() {
      if (cartProductsBuilder_ == null) {
        return cartProducts_.size();
      } else {
        return cartProductsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public org.dataaccess.protobuf.Cart getCartProducts(int index) {
      if (cartProductsBuilder_ == null) {
        return cartProducts_.get(index);
      } else {
        return cartProductsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder setCartProducts(
        int index, org.dataaccess.protobuf.Cart value) {
      if (cartProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartProductsIsMutable();
        cartProducts_.set(index, value);
        onChanged();
      } else {
        cartProductsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder setCartProducts(
        int index, org.dataaccess.protobuf.Cart.Builder builderForValue) {
      if (cartProductsBuilder_ == null) {
        ensureCartProductsIsMutable();
        cartProducts_.set(index, builderForValue.build());
        onChanged();
      } else {
        cartProductsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder addCartProducts(org.dataaccess.protobuf.Cart value) {
      if (cartProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartProductsIsMutable();
        cartProducts_.add(value);
        onChanged();
      } else {
        cartProductsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder addCartProducts(
        int index, org.dataaccess.protobuf.Cart value) {
      if (cartProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartProductsIsMutable();
        cartProducts_.add(index, value);
        onChanged();
      } else {
        cartProductsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder addCartProducts(
        org.dataaccess.protobuf.Cart.Builder builderForValue) {
      if (cartProductsBuilder_ == null) {
        ensureCartProductsIsMutable();
        cartProducts_.add(builderForValue.build());
        onChanged();
      } else {
        cartProductsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder addCartProducts(
        int index, org.dataaccess.protobuf.Cart.Builder builderForValue) {
      if (cartProductsBuilder_ == null) {
        ensureCartProductsIsMutable();
        cartProducts_.add(index, builderForValue.build());
        onChanged();
      } else {
        cartProductsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder addAllCartProducts(
        java.lang.Iterable<? extends org.dataaccess.protobuf.Cart> values) {
      if (cartProductsBuilder_ == null) {
        ensureCartProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cartProducts_);
        onChanged();
      } else {
        cartProductsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder clearCartProducts() {
      if (cartProductsBuilder_ == null) {
        cartProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cartProductsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public Builder removeCartProducts(int index) {
      if (cartProductsBuilder_ == null) {
        ensureCartProductsIsMutable();
        cartProducts_.remove(index);
        onChanged();
      } else {
        cartProductsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public org.dataaccess.protobuf.Cart.Builder getCartProductsBuilder(
        int index) {
      return getCartProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public org.dataaccess.protobuf.CartOrBuilder getCartProductsOrBuilder(
        int index) {
      if (cartProductsBuilder_ == null) {
        return cartProducts_.get(index);  } else {
        return cartProductsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public java.util.List<? extends org.dataaccess.protobuf.CartOrBuilder> 
         getCartProductsOrBuilderList() {
      if (cartProductsBuilder_ != null) {
        return cartProductsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cartProducts_);
      }
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public org.dataaccess.protobuf.Cart.Builder addCartProductsBuilder() {
      return getCartProductsFieldBuilder().addBuilder(
          org.dataaccess.protobuf.Cart.getDefaultInstance());
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public org.dataaccess.protobuf.Cart.Builder addCartProductsBuilder(
        int index) {
      return getCartProductsFieldBuilder().addBuilder(
          index, org.dataaccess.protobuf.Cart.getDefaultInstance());
    }
    /**
     * <code>repeated .Cart cartProducts = 1;</code>
     */
    public java.util.List<org.dataaccess.protobuf.Cart.Builder> 
         getCartProductsBuilderList() {
      return getCartProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.dataaccess.protobuf.Cart, org.dataaccess.protobuf.Cart.Builder, org.dataaccess.protobuf.CartOrBuilder> 
        getCartProductsFieldBuilder() {
      if (cartProductsBuilder_ == null) {
        cartProductsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.dataaccess.protobuf.Cart, org.dataaccess.protobuf.Cart.Builder, org.dataaccess.protobuf.CartOrBuilder>(
                cartProducts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cartProducts_ = null;
      }
      return cartProductsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CartItems)
  }

  // @@protoc_insertion_point(class_scope:CartItems)
  private static final org.dataaccess.protobuf.CartItems DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.dataaccess.protobuf.CartItems();
  }

  public static org.dataaccess.protobuf.CartItems getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CartItems>
      PARSER = new com.google.protobuf.AbstractParser<CartItems>() {
    @java.lang.Override
    public CartItems parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CartItems(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CartItems> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartItems> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.dataaccess.protobuf.CartItems getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

