// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface CartItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CartItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 cartId = 2;</code>
   * @return The cartId.
   */
  int getCartId();

  /**
   * <code>int32 productId = 3;</code>
   * @return The productId.
   */
  int getProductId();
}
