// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface CartItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CartItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  java.util.List<org.dataaccess.protobuf.CartItem> 
      getCartItemsList();
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  org.dataaccess.protobuf.CartItem getCartItems(int index);
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  java.util.List<? extends org.dataaccess.protobuf.CartItemOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  org.dataaccess.protobuf.CartItemOrBuilder getCartItemsOrBuilder(
      int index);
}
