// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface CartItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CartItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  java.util.List<org.dataaccess.protobuf.Cart> 
      getCartProductsList();
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  org.dataaccess.protobuf.Cart getCartProducts(int index);
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  int getCartProductsCount();
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  java.util.List<? extends org.dataaccess.protobuf.CartOrBuilder> 
      getCartProductsOrBuilderList();
  /**
   * <code>repeated .Cart cartProducts = 1;</code>
   */
  org.dataaccess.protobuf.CartOrBuilder getCartProductsOrBuilder(
      int index);
}
