// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface CategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Category)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string category_name = 1;</code>
   * @return The categoryName.
   */
  java.lang.String getCategoryName();
  /**
   * <code>string category_name = 1;</code>
   * @return The bytes for categoryName.
   */
  com.google.protobuf.ByteString
      getCategoryNameBytes();
}
