// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface CreditsUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreditsUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 credits = 1;</code>
   * @return The credits.
   */
  int getCredits();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
