// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface ProductItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Product product = 1;</code>
   */
  java.util.List<org.dataaccess.protobuf.Product> 
      getProductList();
  /**
   * <code>repeated .Product product = 1;</code>
   */
  org.dataaccess.protobuf.Product getProduct(int index);
  /**
   * <code>repeated .Product product = 1;</code>
   */
  int getProductCount();
  /**
   * <code>repeated .Product product = 1;</code>
   */
  java.util.List<? extends org.dataaccess.protobuf.ProductOrBuilder> 
      getProductOrBuilderList();
  /**
   * <code>repeated .Product product = 1;</code>
   */
  org.dataaccess.protobuf.ProductOrBuilder getProductOrBuilder(
      int index);
}
