// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface SearchFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string search = 1;</code>
   * @return The search.
   */
  java.lang.String getSearch();
  /**
   * <code>string search = 1;</code>
   * @return The bytes for search.
   */
  com.google.protobuf.ByteString
      getSearchBytes();
}
