// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface UsersExistOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsersExist)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .User users = 1;</code>
   */
  java.util.List<org.dataaccess.protobuf.User> 
      getUsersList();
  /**
   * <code>repeated .User users = 1;</code>
   */
  org.dataaccess.protobuf.User getUsers(int index);
  /**
   * <code>repeated .User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .User users = 1;</code>
   */
  java.util.List<? extends org.dataaccess.protobuf.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .User users = 1;</code>
   */
  org.dataaccess.protobuf.UserOrBuilder getUsersOrBuilder(
      int index);
}
